version: "3.9"

services:
  app:
    image: game-server:latest
    container_name: game-server
    restart: always
    ports:
      - "127.0.0.1:14527:14527"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  nginx:
    image: nginx:1.25
    container_name: game-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
    depends_on:
      - app
